"""Shared platform package for Appointment Agent v1.0.0."""

from .commands import (
    CallbackPayload,
    CancelBookingCommand,
    CancelJourneyCommand,
    ConfirmJourneyCommand,
    CreateBookingCommand,
    HandleProviderCallbackCommand,
    HoldSlotCommand,
    LekabDispatchCommand,
    LaunchAppointmentWorkflowCommand,
    ReleaseSlotHoldCommand,
    ReminderCommand,
    ResolveCustomerCommand,
    SearchSlotsCommand,
    SelectSlotCommand,
    StartJourneyCommand,
    UpdateBookingCommand,
    UpsertCustomerCommand,
)
from .enums import BookingStatus, ErrorCategory, JourneyState, SlotHoldStatus
from .errors import ProviderError, SharedError
from .events import CommandEnvelope, EventEnvelope
from .ids import new_id
from .models import (
    AppointmentBooking,
    AppointmentJourney,
    AppointmentJourneyRecord,
    AppointmentPreference,
    BookingRecord,
    BookingResult,
    CallbackReceipt,
    CandidateSlot,
    ContactRecord,
    ConversationTurn,
    ConversationTurnPayload,
    ConversationTurnRecord,
    CustomerProfile,
    ProviderReference,
    SlotHold,
)
from .validators import require_non_empty, validate_iso_datetime

__all__ = [
    "AppointmentBooking",
    "AppointmentJourney",
    "AppointmentJourneyRecord",
    "AppointmentPreference",
    "BookingRecord",
    "BookingResult",
    "BookingStatus",
    "CallbackReceipt",
    "CallbackPayload",
    "CancelBookingCommand",
    "CancelJourneyCommand",
    "CandidateSlot",
    "CommandEnvelope",
    "ConfirmJourneyCommand",
    "ContactRecord",
    "ConversationTurn",
    "ConversationTurnPayload",
    "ConversationTurnRecord",
    "CreateBookingCommand",
    "CustomerProfile",
    "EventEnvelope",
    "HandleProviderCallbackCommand",
    "HoldSlotCommand",
    "JourneyState",
    "LekabDispatchCommand",
    "LaunchAppointmentWorkflowCommand",
    "ProviderError",
    "ProviderReference",
    "ReleaseSlotHoldCommand",
    "ReminderCommand",
    "ResolveCustomerCommand",
    "SearchSlotsCommand",
    "SelectSlotCommand",
    "SharedError",
    "SlotHold",
    "SlotHoldStatus",
    "StartJourneyCommand",
    "UpdateBookingCommand",
    "UpsertCustomerCommand",
    "ErrorCategory",
    "new_id",
    "require_non_empty",
    "validate_iso_datetime",
]
