from enum import Enum


class JourneyState(str, Enum):
    NEW = "NEW"
    IDENTIFYING_CUSTOMER = "IDENTIFYING_CUSTOMER"
    COLLECTING_PREFERENCES = "COLLECTING_PREFERENCES"
    SEARCHING_SLOTS = "SEARCHING_SLOTS"
    OFFERING_SLOTS = "OFFERING_SLOTS"
    WAITING_FOR_SELECTION = "WAITING_FOR_SELECTION"
    HOLDING_SLOT = "HOLDING_SLOT"
    WAITING_FOR_CONFIRMATION = "WAITING_FOR_CONFIRMATION"
    BOOKING_APPOINTMENT = "BOOKING_APPOINTMENT"
    BOOKED = "BOOKED"
    REMINDER_PENDING = "REMINDER_PENDING"
    RESCHEDULE_FLOW = "RESCHEDULE_FLOW"
    CANCELLATION_FLOW = "CANCELLATION_FLOW"
    ESCALATED = "ESCALATED"
    CLOSED = "CLOSED"
    FAILED = "FAILED"


class BookingStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    RESCHEDULED = "RESCHEDULED"
    CANCELLED = "CANCELLED"
    FAILED = "FAILED"


class SlotHoldStatus(str, Enum):
    ACTIVE = "ACTIVE"
    EXPIRED = "EXPIRED"
    RELEASED = "RELEASED"
    CONSUMED = "CONSUMED"


class ErrorCategory(str, Enum):
    VALIDATION = "VALIDATION"
    AUTH = "AUTH"
    PERMISSION = "PERMISSION"
    NOT_FOUND = "NOT_FOUND"
    CONFLICT = "CONFLICT"
    POLICY = "POLICY"
    TIMEOUT = "TIMEOUT"
    UPSTREAM_4XX = "UPSTREAM_4XX"
    UPSTREAM_5XX = "UPSTREAM_5XX"
    NETWORK = "NETWORK"
    DUPLICATE = "DUPLICATE"
    MAPPING = "MAPPING"
    UNKNOWN = "UNKNOWN"
